Quiz 17 — Broadcasting
Theme  : Grocery Discounts
Topics : broadcasting scalar, broadcasting 1-D over 2-D

SCENARIO
A supermarket has 3 product categories, 4 items each.
Original prices (£):
prices = [[1.20, 2.50, 0.80, 3.00],   # Fruit
           [4.50, 5.20, 3.80, 6.00],   # Meat
           [0.60, 1.10, 0.90, 1.50]]   # Dairy

TASKS
1. Create the 2-D array.
2. Apply a 10% discount to ALL items (broadcast scalar).
3. Apply category-specific discounts: Fruit 5%, Meat 15%, Dairy 8%.
   Use a (3,1) discount column vector so broadcasting works correctly.
4. Print both discounted price tables, rounded to 2 dp.

EXPECTED OUTPUT
10% off (all)   :
[[1.08 2.25 0.72 2.7 ] [4.05 4.68 3.42 5.4 ] [0.54 0.99 0.81 1.35]]
Category discounts:
[[1.14 2.375 0.76 2.85] [3.825 4.42 3.23 5.1] [0.552 1.012 0.828 1.38]]

In [88]:
import numpy as np

prices = [[1.20, 2.50, 0.80, 3.00],
          [4.50, 5.20, 3.80, 6.00],
          [0.60, 1.10, 0.90, 1.50]]

# ── write your solution below ──────────────────────────────────────────────

arr_pr = np.array(prices)

print("real Price :",arr_pr)

discount_10off = (arr_pr * 0.10 )

add_discount = arr_pr - discount_10off

print(discount)

print("Adding 10 off discount  :",add_discount)
#-------------------------------------------------
fruit = arr_pr[0:1]

print("Fruit cat.  :", fruit)

Meat = arr_pr[1:2]
print("Meat cat   :", Meat)

Dairy = arr_pr[2::]
print("Dairy cat   :", Dairy)

off5frt = fruit - (fruit * 0.05)
print("5% off fruit", off5frt)

off15met = Meat - (Meat * 0.15)
print("15% off meat", off15met)

print("8% off Dairy", Dairy - (Dairy * 0.08))


real Price : [[1.2 2.5 0.8 3. ]
 [4.5 5.2 3.8 6. ]
 [0.6 1.1 0.9 1.5]]
[[0.12 0.25 0.08 0.3 ]
 [0.45 0.52 0.38 0.6 ]
 [0.06 0.11 0.09 0.15]]
Adding 10 off discount  : [[1.08 2.25 0.72 2.7 ]
 [4.05 4.68 3.42 5.4 ]
 [0.54 0.99 0.81 1.35]]
Fruit cat.  : [[1.2 2.5 0.8 3. ]]
Meat cat   : [[4.5 5.2 3.8 6. ]]
Dairy cat   : [[0.6 1.1 0.9 1.5]]
5% off fruit [[1.14  2.375 0.76  2.85 ]]
15% off meat [[3.825 4.42  3.23  5.1  ]]
8% off Dairy [[0.552 1.012 0.828 1.38 ]]


In [58]:
furt = arr_pr[1:2]
print(furt)

[[4.5 5.2 3.8 6. ]]
