Quiz 02 — Indexing + Slicing (2-D)
Theme  : Hotel Guests
Topics : 2-D array creation, row/column slicing, shape

SCENARIO
A hotel tracks check-ins for 4 floors, each with 5 rooms.
guests = [[2,0,1,3,2],
           [1,1,0,2,3],
           [3,2,1,0,1],
           [0,1,2,3,2]]
Each value = number of guests currently in that room.

TASKS
1. Create a 2-D NumPy array from the data above.
2. Print the shape of the array.
3. Print all rooms on floor 3 (row index 2).
4. Print the guest count of room 4 on every floor (column index 3).
5. Print the sub-grid covering floors 2–3, rooms 2–4 (0-indexed 1:3, 1:4).

EXPECTED OUTPUT
Shape        : (4, 5)
Floor 3      : [3 2 1 0 1]
Room 4 all   : [3 2 0 3]
Sub-grid     :
[[1 0 2]
 [2 1 0]]

In [32]:
import numpy as np

guests = np.array(
    [[2,0,1,3,2],
          [1,1,0,2,3],
          [3,2,1,0,1],
          [0,1,2,3,2]]
          )

# ── write your solution below ──────────────────────────────────────────────

print(np.shape(guests))
print(guests[2])
print("Room 4 all   :", guests[:, 3])
print(guests[1:3, 1:4])

(4, 5)
[3 2 1 0 1]
Room 4 all   : [3 2 0 3]
[[1 0 2]
 [2 1 0]]
