Quiz 03 — Shape, ndim, size
Theme  : University Marks
Topics : .shape, .ndim, .size, .dtype

SCENARIO
A university records exam marks for 3 courses, 6 students each.
marks = [[72, 85, 60, 91, 55, 78],
          [88, 74, 69, 95, 82, 71],
          [60, 77, 83, 68, 90, 65]]

TASKS
1. Create the NumPy array.
2. Print its shape, ndim, size, and dtype.
3. Print the total number of students × courses (size).
4. Print the mark of the 2nd student in the 3rd course (0-indexed: row 2, col 1).
5. Print the entire 2nd course (row 1).

EXPECTED OUTPUT
Shape : (3, 6)  |  ndim : 2  |  size : 18  |  dtype : int64
Total entries : 18
Mark [course 3, student 2] : 77
Course 2 marks : [88 74 69 95 82 71]

In [ ]:
import numpy as np

marks = np.array([[72, 85, 60, 91, 55, 78],
         [88, 74, 69, 95, 82, 71],
         [60, 77, 83, 68, 90, 65]])

# ── write your solution below ──────────────────────────────────────────────

print(marks)
print("Shape", np.shape(marks), "ndim", np.ndim(marks), "size", np.size(marks),(marks.dtype))
total = np.size(marks) #Jami elementlar soni
print(np.sum(total))
print(marks[2, 1])
print(marks[1])

#for stesting
#for stesting
#for stesting

[[72 85 60 91 55 78]
 [88 74 69 95 82 71]
 [60 77 83 68 90 65]]
Shape (3, 6) ndim 2 size 18 int64
18
77
[88 74 69 95 82 71]
