Quiz 08 — 2-D Slicing  [SOLVED]
Theme  : E-commerce Orders
Topics : axis=0/1 sum, column slicing, row slicing

In [1]:
import numpy as np

orders = np.array([[200,150,80,300,120],
                   [180,200,90,280,140],
                   [220,170,70,320,160],
                   [190,160,85,310,130]])

# axis=1 collapses columns → one sum per row
print("Orders per week    :", orders.sum(axis=1))    # [850 890 940 875]

# axis=0 collapses rows → one sum per column
print("Orders per category:", orders.sum(axis=0))    # [790 680 325 1210 550]

# All rows (:), first two columns (0:2)
print("Electronics+Cloth  :")
print(orders[:, 0:2])

# Rows 1 and 2 (weeks 2 and 3)
print("Weeks 2-3   :")
print(orders[1:3])

# ── WHY ────────────────────────────────────────────────────────────────────
# axis=0 → operation runs *down* the rows (collapses rows, keeps cols).
# axis=1 → operation runs *across* columns (collapses cols, keeps rows).
# This is a common point of confusion — think "which axis disappears."

Orders per week    : [850 890 940 875]
Orders per category: [ 790  680  325 1210  550]
Electronics+Cloth  :
[[200 150]
 [180 200]
 [220 170]
 [190 160]]
Weeks 2-3   :
[[180 200  90 280 140]
 [220 170  70 320 160]]
